      <div class="grid_3" id="Sidebar">
        <div id="Navigation">
          <div id="Logotype">
            <img src="/images/logoIets.png" alt="Iets" title="Iets" height="113" width="98">
          </div><!-- #Logotype -->
        </div><!-- #Navigation -->
      </div><!-- #Sidebar -->

      <div class="grid_9" id="Main">
        <div id="Header">
          <h1>Sistema de gestão de projetos</h1>
        </div><!-- #Header -->

        <div id="Stage">
          <h1>Login</h1>
            <div id="LoginBox" class="Area">
<!-- content -->
<?php echo $this->layout()->content ?>
<!-- /content -->
            </div><!-- #LoginBox -->
        </div><!-- Stage -->
      </div><!-- #Main -->
