      <div class="grid_3" id="Sidebar">
        <div id="Navigation">
          <div id="Logotype">
            <img src="/images/logoIets.png" alt="Iets" title="Iets" height="113" width="98">
          </div><!-- #Logotype -->
          <ul>
            <li><a href="/projects/">Projetos</a></li>
            <li><a href="/register/">Cadastro</a></li>
          </ul>
      </div><!-- #Navigation -->
      </div><!-- #Sidebar -->

      <div class="grid_9" id="Main">
        <div id="Header">
          <h1>Sistema de gestão de projetos</h1>
<?php
if ($this->saudacaoUsuario['logado']) {
?>
          <!-- logado -->
          <div id="User">
            <p>
              Ol&aacute; <?php echo $this->saudacaoUsuario['nome_usuario']?>
            </p>
            <p>
              <a href="/auth/logout">Log out</a>
            </p>
            <p>
              <a href="#"><img src="public/images/icoMensagens.png" alt="Mensagens" title="Mensagens" height="18" width="19"></a>
            </p>
            <p>
              <a href="<?php echo $this->saudacaoUsuario['link_edita']?>"><img src="public/images/icoConfigs.png" alt="Seus dados" title="Seus dados" height="19" width="23"></a>
            </p>
          </div><!-- #User -->
          <!-- /logado -->
<?php
} else {
?>
          <!-- nao logado -->
          <div id="User">
            <p class="caption_4">
              Voc&ecirc; ainda n&atilde;o se identificou.
            </p>
          </div><!-- #User -->
          <!-- /nao logado -->
<?php
}
?>
        </div><!-- #Header -->

        <div id="Stage">
<!-- content -->
<?php echo $this->layout()->content; ?>
<!-- /content -->
        </div><!-- Stage -->
      </div><!-- #Main -->
