<!DOCTYPE HTML>
<html>
  <head>
    <title><?php echo $this->layout()->title?></title>
<?php include ("meta.phtml") ?>
    <link rel="stylesheet" type="text/css" href="/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/css/grid.css">
    <link rel="stylesheet" type="text/css" href="/css/styles.css" media="screen">
    <link rel="stylesheet" type="text/css" href="/css/css3.css" media="screen">
    <link rel="stylesheet" type="text/css" href="/css/formalize.css">
    <!-- 
    <link rel="stylesheet" type="text/css" href="/css/forms.css" media="screen">
     -->
<?php
$this->dojo()->setDjConfigOption('usePlainJson',true)
        ->addStylesheetModule('dijit.themes.tundra')
        ->setLocalPath("/js/dojo/dojo/dojo.js");
    
echo $this->dojo();
?>

    <script type="text/javascript" src="/js/prototype.js"></script>
    <script type="text/javascript" src="/js/ajax_funcs.js"></script>

    <link rel="stylesheet" type="text/css" href="/css/tabl.css" />
    <link rel="stylesheet" type="text/css" href="/css/flexigrid.css" />
    <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/flexigrid.js"></script>

    <link rel="stylesheet" type="text/css" href="/css/dropmenu.css" />

    <link rel="stylesheet" type="text/css" href="/css/anylinkcssmenu.css" />
    <script type="text/javascript" src="/js/anylinkcssmenu.js"></script>
    <script type="text/javascript">
      anylinkcssmenu.init("anchorclass")
    </script>
  </head>
  <body class="nihilo">
    <div class="container_12" id="Envelope">
<?php
  if ($this->layout()->nestedLayout) {
      $this->layout()->setLayout($this->layout()->nestedLayout);   
  } else {
      $this->layout()->setLayout('inner');
  }
  echo $this->layout()->render();
?>
<!-- footer -->
<?php //echo $this->action('inclui', 'footer', 'includes') ?>
<!-- /footer -->
    </div><!-- #Envelope -->
  </body>
</html>